import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react';
import { io, Socket } from 'socket.io-client';

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:4000';
type User = { id: string; name: string; email: string };
type Member = { id: string; role: string; user: User };
type Column = { id: string; name: string; position: number };
type Task = { id: string; title: string; description?: string | null; priority: string; dueDate?: string | null; position: number; columnId: string; column: Column; assignee?: User | null; creator: User; _count: { comments: number } };
type Project = { id: string; name: string; description?: string | null; members: Member[]; columns: Column[]; tasks: Task[]; _count?: { tasks: number } };
type Notification = { id: string; message: string; read: boolean; createdAt: string };
type Comment = { id: string; body: string; createdAt: string; author: User };

aasync function request<T>(path: string, options: RequestInit = {}, token?: string): Promise<T> {
  const res = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers ?? {}) } });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error ?? 'Request failed');
  return data;
}

export default function App() {
  const [token, setToken] = useState(localStorage.getItem('projectflow_token') ?? '');
  const [user, setUser] = useState<User | null>(null);
  const [authMode, setAuthMode] = useState<'login' | 'register'>('login');
  const [projects, setProjects] = useState<Project[]>([]);
  const [active, setActive] = useState<Project | null>(null);
  const [view, setView] = useState<'overview' | 'board' | 'list' | 'calendar' | 'activity' | 'members'>('overview');
  const [query, setQuery] = useState('');
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [error, setError] = useState('');
  const [showCreateProject, setShowCreateProject] = useState(false);
  const [showCreateTask, setShowCreateTask] = useState<string | null>(null);
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const [socket, setSocket] = useState<Socket | null>(null);

  useEffect(() => {
    if (!token) return;
    localStorage.setItem('projectflow_token', token);
    request<User>('/api/auth/me', {}, token).then(setUser).catch(() => { localStorage.removeItem('projectflow_token'); setToken(''); });
    request<Project[]>('/api/projects', {}, token).then(setProjects).catch(e => setError(e.message));
    request<Notification[]>('/api/notifications', {}, token).then(setNotifications).catch(() => undefined);
    const s = io(API, { auth: { token } });
    s.on('notification:created', (n: Notification) => setNotifications(prev => [n, ...prev]));
    s.on('task:updated', (task: Task) => setActive(prev => prev ? { ...prev, tasks: prev.tasks.map(t => t.id === task.id ? task : t) } : prev));
    s.on('task:created', (task: Task) => setActive(prev => prev ? { ...prev, tasks: [...prev.tasks, task] } : prev));
    setSocket(s);
    return () => { s.disconnect(); setSocket(null); };
  }, [token]);

  const openProject = async (id: string) => {
    try { const project = await request<Project>(`/api/projects/${id}`, {}, token); setActive(project); setView('overview'); socket?.emit('project:join', id); }
    catch (e) { setError((e as Error).message); }
  };
  const logout = () => { localStorage.removeItem('projectflow_token'); setToken(''); setUser(null); setActive(null); setProjects([]); };
  if (!token || !user) return <Auth mode={authMode} setMode={setAuthMode} onAuth={(t, u) => { setToken(t); setUser(u); }} error={error} />;

  const unread = notifications.filter(n => !n.read).length;
  return <div className="app-shell">
    <header className="product-topbar">
      <div className="product-brand" onClick={() => setActive(null)}><span className="brand-mark">PF</span><span>ProjectFlow</span></div>
      <div className="global-search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search projects and tasks" /><kbd>⌘ K</kbd></div>
      <div className="top-actions"><button className="top-icon" title="Notifications" onClick={() => setNotifications(prev => prev.map(n => ({ ...n, read: true })))}>♢{unread > 0 && <b>{unread}</b>}</button><div className="user-chip"><span className="avatar">{user.name.slice(0,1).toUpperCase()}</span><span>{user.name}</span></div><button className="ghost" onClick={logout}>Log out</button></div>
    </header>
    {error && <div className="error-banner" onClick={() => setError('')}>{error}</div>}
    <div className="product-layout">
      <aside className="product-sidebar">
        <div className="workspace-switch"><span className="workspace-logo">P</span><div><strong>Personal workspace</strong><small>{user.email}</small></div><span>⌄</span></div>
        <nav className="primary-nav"><button className={!active ? 'active' : ''} onClick={() => setActive(null)}>⌂ <span>Home</span></button><button>◷ <span>My work</span></button><button>▣ <span>Calendar</span></button><button>✦ <span>Inbox</span>{unread > 0 && <em>{unread}</em>}</button></nav>
        <div className="side-section"><div className="side-section-title"><span>Projects</span><button onClick={() => setShowCreateProject(true)}>＋</button></div>{projects.map((p, i) => <button key={p.id} className={`side-project ${active?.id === p.id ? 'active' : ''}`} onClick={() => openProject(p.id)}><span className={`project-dot dot-${i % 4}`}></span><span>{p.name}</span><small>{p._count?.tasks ?? p.tasks?.length ?? 0}</small></button>)}{projects.length === 0 && <p className="side-empty">No projects yet.</p>}</div>
        <div className="sidebar-bottom"><button>⚙ <span>Settings</span></button><button>?</button></div>
      </aside>
      <main className="product-main">
        {active ? <ProjectWorkspace project={active} token={token} user={user} view={view} setView={setView} query={query} onRefresh={() => openProject(active.id)} onTask={setSelectedTask} onCreate={setShowCreateTask} /> : <Home projects={projects} user={user} query={query} onCreate={() => setShowCreateProject(true)} onOpen={openProject} />}
      </main>
    </div>
    {showCreateProject && <CreateProject token={token} onClose={() => setShowCreateProject(false)} onCreated={p => { setProjects(prev => [p, ...prev]); setShowCreateProject(false); openProject(p.id); }} />}
    {showCreateTask && active && <CreateTask token={token} project={active} columnId={showCreateTask} onClose={() => setShowCreateTask(null)} onCreated={() => { setShowCreateTask(null); openProject(active.id); }} />}
    {selectedTask && active && <TaskModal token={token} task={selectedTask} project={active} onClose={() => setSelectedTask(null)} onChanged={() => openProject(active.id)} />}
  </div>;
}

function Home({ projects, user, query, onCreate, onOpen }: { projects: Project[]; user: User; query: string; onCreate: () => void; onOpen: (id: string) => void }) {
  const allTasks = projects.reduce((n, p) => n + (p._count?.tasks ?? p.tasks?.length ?? 0), 0);
  const visible = projects.filter(p => p.name.toLowerCase().includes(query.toLowerCase()));
  return <div className="home-page">
    <section className="hero-row"><div><div className="eyebrow">WORKSPACE / HOME</div><h1>Good afternoon, {user.name.split(' ')[0]}.</h1><p>Everything your team is working on, in one focused place.</p></div><button className="primary" onClick={onCreate}>＋ New project</button></section>
    <section className="stats-row"><Stat label="Projects" value={projects.length} icon="◇"/><Stat label="Open work" value={allTasks} icon="✓"/><Stat label="Team members" value={projects.reduce((n,p)=>n+p.members.length,0)} icon="◉"/><Stat label="Unread" value={0} icon="✦"/></section>
    <section className="section-block"><div className="section-heading"><div><h2>Your projects</h2><p>Jump back into active work.</p></div><button className="text-button" onClick={onCreate}>Create project →</button></div>{visible.length ? <div className="project-cards">{visible.map((p, i) => <ProjectCard key={p.id} project={p} index={i} onClick={() => onOpen(p.id)} />)}</div> : <div className="empty-card"><h3>No matching projects</h3><p>Try another search or create a new workspace.</p></div>}</section>
    <section className="home-bottom"><div className="focus-card"><div className="eyebrow">TODAY</div><h2>Keep momentum visible.</h2><p>Use a project board to turn planning into visible progress, assign work, and keep conversations attached to the task.</p><button className="dark-link" onClick={onCreate}>Start a project →</button></div><div className="quick-card"><span className="quick-icon">⌁</span><div><strong>Live collaboration</strong><p>Task changes and notifications update through the real-time workspace.</p></div></div></section>
  </div>;
}

function Stat({ label, value, icon }: { label: string; value: number; icon: string }) { return <div className="stat-card"><span className="stat-glyph">{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>; }
function ProjectCard({ project, index, onClick }: { project: Project; index: number; onClick: () => void }) {
  const total = project.tasks.length || project._count?.tasks || 0; const done = project.columns.find(c => /done|complete/i.test(c.name)); const doneCount = done ? project.tasks.filter(t => t.columnId === done.id).length : 0; const progress = total ? Math.round(doneCount / total * 100) : 0;
  return <button className="project-card-new" onClick={onClick}><div className="project-card-top"><span className={`project-symbol-new symbol-${index % 4}`}>{project.name.slice(0,1).toUpperCase()}</span><span className="card-arrow">↗</span></div><h3>{project.name}</h3><p>{project.description || 'Collaborative project workspace'}</p><div className="card-progress"><div><span>Progress</span><b>{progress}%</b></div><div className="progress-track"><i style={{ width: `${progress}%` }} /></div></div><div className="card-foot"><span>{total} tasks</span><span>{project.members.length} members</span></div></button>;
}

function ProjectWorkspace({ project, token, user, view, setView, query, onRefresh, onTask, onCreate }: { project: Project; token: string; user: User; view: string; setView: (v: any) => void; query: string; onRefresh: () => void; onTask: (t: Task) => void; onCreate: (columnId: string) => void }) {
  const tabs = ['overview','board','list','calendar','activity','members'];
  return <div className="project-page"><div className="project-hero"><div><div className="breadcrumb">Projects <span>/</span> {project.name}</div><div className="project-title-row"><span className="project-symbol-large">{project.name.slice(0,1).toUpperCase()}</span><div><h1>{project.name}</h1><p>{project.description || 'A shared space for planning, execution and collaboration.'}</p></div></div></div><div className="project-actions"><div className="avatar-stack">{project.members.slice(0,5).map(m => <span className="avatar" key={m.id} title={m.user.email}>{m.user.name.slice(0,1).toUpperCase()}</span>)}{project.members.length > 5 && <span className="avatar more">+{project.members.length - 5}</span>}</div><button className="ghost">Share</button><button className="primary" onClick={() => onCreate(project.columns[0]?.id ?? '')}>＋ Add task</button></div></div><div className="workspace-tabs">{tabs.map(t => <button key={t} className={view === t ? 'selected' : ''} onClick={() => setView(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{view === 'overview' && <Overview project={project} onBoard={() => setView('board')} />}{view === 'board' && <Board project={project} token={token} onRefresh={onRefresh} onTask={onTask} onCreate={onCreate} />}{view === 'list' && <TaskList project={project} query={query} onTask={onTask} />}{view === 'calendar' && <CalendarView project={project} />}{view === 'activity' && <ActivityView project={project} />}{view === 'members' && <MembersView project={project} user={user} />}</div>;
}

function Overview({ project, onBoard }: { project: Project; onBoard: () => void }) { const total=project.tasks.length; const doneColumn=project.columns.find(c=>/done|complete/i.test(c.name)); const done=doneColumn ? project.tasks.filter(t=>t.columnId===doneColumn.id).length : 0; const urgent=project.tasks.filter(t=>/urgent|high/i.test(t.priority)).length; const progress=total?Math.round(done/total*100):0; return <div className="overview-page"><div className="overview-grid-new"><div className="progress-hero"><div className="eyebrow">PROJECT HEALTH</div><h2>Work is moving forward.</h2><p>Track execution across the board and keep ownership clear.</p><div className="big-number">{progress}%</div><div className="progress-track"><i style={{width:`${progress}%`}} /></div><div className="hero-meta"><span>{done} completed</span><span>{total-done} remaining</span></div></div><div className="health-card"><span className="health-ring">{project.members.length}</span><div><strong>Team members</strong><p>People collaborating in this project.</p></div><button className="text-button" onClick={onBoard}>Open board →</button></div></div><div className="mini-stat-grid"><Mini label="Total tasks" value={total}/><Mini label="Completed" value={done}/><Mini label="High priority" value={urgent}/><Mini label="Columns" value={project.columns.length}/></div><div className="overview-lower"><div className="surface-card"><div className="section-heading"><div><h2>Work distribution</h2><p>Tasks grouped by current stage.</p></div></div>{project.columns.map(c=>{const count=project.tasks.filter(t=>t.columnId===c.id).length;return <div className="distribution" key={c.id}><div><span>{c.name}</span><b>{count}</b></div><div className="progress-track"><i style={{width:`${total?count/total*100:0}%`}}/></div></div>})}</div><div className="surface-card"><div className="section-heading"><div><h2>Latest work</h2><p>Recent tasks in this project.</p></div></div>{project.tasks.slice(0,4).map(t=><button className="compact-task" key={t.id} onClick={()=>{}}><span className={`priority-dot ${t.priority.toLowerCase()}`}/><span>{t.title}</span><small>{t.assignee?.name || 'Unassigned'}</small></button>)}</div></div></div>; }
function Mini({label,value}:{label:string;value:number}){return <div className="mini-stat"><small>{label}</small><strong>{value}</strong></div>}

function Board({ project, token, onRefresh, onTask, onCreate }: { project: Project; token: string; onRefresh: () => void; onTask: (t: Task) => void; onCreate: (columnId: string) => void }) { const grouped=useMemo(()=>project.columns.map(c=>({...c,tasks:project.tasks.filter(t=>t.columnId===c.id).sort((a,b)=>a.position-b.position)})),[project]); const [dragged,setDragged]=useState<string|null>(null); const move=async(columnId:string)=>{if(!dragged)return;const task=project.tasks.find(t=>t.id===dragged);if(!task||task.columnId===columnId){setDragged(null);return;}try{await request(`/api/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({columnId,position:Date.now()})},token);onRefresh();}catch(e){}setDragged(null);}; return <div className="board-view"><div className="board-toolbar"><div><strong>Board</strong><span>{project.tasks.length} tasks</span></div><div className="live-status"><i/> Live updates</div></div><div className="board-grid-new">{grouped.map((column,index)=><section className={`board-column-new column-accent-${index%4}`} key={column.id} onDragOver={e=>e.preventDefault()} onDrop={()=>move(column.id)}><div className="column-title-new"><span className="column-marker"/><strong>{column.name}</strong><b>{column.tasks.length}</b><button onClick={()=>onCreate(column.id)}>＋</button></div><div className="task-list-new">{column.tasks.map(task=><article className="task-card-new" draggable key={task.id} onDragStart={()=>setDragged(task.id)} onClick={()=>onTask(task)}><div className="task-card-line"><span className={`priority-pill ${task.priority.toLowerCase()}`}>{task.priority}</span>{task.assignee&&<span className="avatar tiny">{task.assignee.name.slice(0,1)}</span>}</div><h3>{task.title}</h3>{task.description&&<p>{task.description.slice(0,110)}{task.description.length>110?'…':''}</p>}<div className="task-bottom"><span>◌ {task._count.comments}</span>{task.dueDate&&<span>{new Date(task.dueDate).toLocaleDateString()}</span>}</div></article>)}{!column.tasks.length&&<div className="column-empty">Drop work here</div>}</div></section>)}</div></div>; }

function TaskList({project,query,onTask}:{project:Project;query:string;onTask:(t:Task)=>void}){const tasks=project.tasks.filter(t=>t.title.toLowerCase().includes(query.toLowerCase()));return <div className="table-surface"><div className="board-toolbar"><div><strong>All work</strong><span>{tasks.length} tasks</span></div></div><table className="work-table"><thead><tr><th>Task</th><th>Status</th><th>Priority</th><th>Assignee</th><th>Comments</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id} onClick={()=>onTask(t)}><td><strong>{t.title}</strong><small>{t.description?.slice(0,60) || 'No description'}</small></td><td><span className="status-pill">{t.column.name}</span></td><td><span className={`priority-pill ${t.priority.toLowerCase()}`}>{t.priority}</span></td><td>{t.assignee?.name || 'Unassigned'}</td><td>{t._count.comments}</td></tr>)}</tbody></table></div>;}
function CalendarView({project}:{project:Project}){const tasks=[...project.tasks].filter(t=>t.dueDate).sort((a,b)=>new Date(a.dueDate!).getTime()-new Date(b.dueDate!).getTime());return <div className="calendar-surface"><div className="calendar-title"><div><div className="eyebrow">SCHEDULE</div><h2>Upcoming work</h2><p>Tasks with due dates in this project.</p></div></div>{tasks.length?tasks.map(t=><div className="calendar-item" key={t.id}><time>{new Date(t.dueDate!).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time><div><strong>{t.title}</strong><small>{t.column.name} · {t.assignee?.name||'Unassigned'}</small></div><span className={`priority-pill ${t.priority.toLowerCase()}`}>{t.priority}</span></div>):<div className="empty-card"><h3>No scheduled tasks</h3><p>Add due dates to make this project calendar useful.</p></div>}</div>;}
function ActivityView({project}:{project:Project}){return <div className="surface-card activity-surface"><div className="eyebrow">PROJECT ACTIVITY</div><h2>Recent work</h2>{project.tasks.slice(0,8).map((t,i)=><div className="activity-item" key={t.id}><span className="activity-avatar">{t.creator.name.slice(0,1)}</span><div><strong>{t.creator.name}</strong><span> created <b>{t.title}</b></span><small>{t.column.name} · {t.priority} priority</small></div><time>{i+1}h ago</time></div>)}</div>;}
function MembersView({project,user}:{project:Project;user:User}){return <div className="members-page-new"><div className="member-intro"><div><div className="eyebrow">TEAM</div><h2>Project members</h2><p>People with access to this workspace.</p></div><button className="primary">＋ Invite member</button></div><div className="member-grid">{project.members.map(m=><div className="member-card" key={m.id}><span className="member-avatar">{m.user.name.slice(0,1).toUpperCase()}</span><div><strong>{m.user.name}</strong><small>{m.user.email}</small></div><span className="role-pill">{m.role}{m.user.id===user.id?' · You':''}</span></div>)}</div></div>;}

function Auth({mode,setMode,onAuth,error}:{mode:'login'|'register';setMode:(m:'login'|'register')=>void;onAuth:(token:string,user:User)=>void;error:string}){const[name,setName]=useState('');const[email,setEmail]=useState('demo@projectflow.local');const[password,setPassword]=useState('ProjectFlow123!');const[busy,setBusy]=useState(false);const[localError,setLocalError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setLocalError('');try{const data=await request<{token:string,user:User}>(`/api/auth/${mode}`,{method:'POST',body:JSON.stringify(mode==='login'?{email,password}:{name,email,password})});onAuth(data.token,data.user);}catch(e){setLocalError((e as Error).message);}finally{setBusy(false);}};return <div className="auth-page-new"><div className="auth-story"><div className="brand-big"><span className="brand-mark">PF</span> ProjectFlow</div><div><div className="eyebrow">COLLABORATIVE WORK MANAGEMENT</div><h1>Make work<br/><em>visible.</em></h1><p>Plan projects, coordinate people, and move tasks forward without losing the conversation.</p></div><div className="story-board"><span/><span/><span/><span/></div></div><form className="auth-card auth-card-new" onSubmit={submit}><div className="auth-mobile-brand">PF / ProjectFlow</div><div className="eyebrow">YOUR WORKSPACE</div><h2>{mode==='login'?'Welcome back.':'Create your workspace.'}</h2><p>Sign in to continue to your projects.</p>{mode==='register'&&<label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{(localError||error)&&<div className="form-error">{localError||error}</div>}<button className="primary auth-submit" disabled={busy}>{busy?'Signing in…':mode==='login'?'Sign in':'Create account'}</button><button type="button" className="link-button" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create an account →':'← Back to sign in'}</button></form></div>;}

function CreateProject({token,onClose,onCreated}:{token:string;onClose:()=>void;onCreated:(p:Project)=>void}){const[name,setName]=useState('');const[description,setDescription]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{const p=await request<Project>('/api/projects',{method:'POST',body:JSON.stringify({name,description})},token);onCreated(p);}catch(e){alert((e as Error).message)}};return <Modal title="Create project" onClose={onClose}><form onSubmit={submit} className="form"><label>Project name<input autoFocus value={name} onChange={e=>setName(e.target.value)} required/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is this team building?"/></label><button className="primary">Create project</button></form></Modal>;}
function CreateTask({token,project,columnId,onClose,onCreated}:{token:string;project:Project;columnId:string;onClose:()=>void;onCreated:()=>void}){const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[priority,setPriority]=useState('MEDIUM');const[assigneeId,setAssigneeId]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await request(`/api/projects/${project.id}/tasks`,{method:'POST',body:JSON.stringify({title,description,priority,columnId,assigneeId:assigneeId||null})},token);onCreated();}catch(e){alert((e as Error).message)}};return <Modal title="Create task" onClose={onClose}><form onSubmit={submit} className="form"><label>Task title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="two"><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></label><label>Assignee<select value={assigneeId} onChange={e=>setAssigneeId(e.target.value)}><option value="">Unassigned</option>{project.members.map(m=><option key={m.user.id} value={m.user.id}>{m.user.name}</option>)}</select></label></div><button className="primary">Create task</button></form></Modal>;}
function TaskModal({token,task,project,onClose,onChanged}:{token:string;task:Task;project:Project;onClose:()=>void;onChanged:()=>void}){const[comments,setComments]=useState<Comment[]>([]);const[body,setBody]=useState('');const[saving,setSaving]=useState(false);useEffect(()=>{request<Comment[]>(`/api/tasks/${task.id}/comments`,{},token).then(setComments).catch(()=>undefined)},[task.id,token]);const save=async(e:FormEvent)=>{e.preventDefault();if(!body.trim())return;setSaving(true);try{const c=await request<Comment>(`/api/tasks/${task.id}/comments`,{method:'POST',body:JSON.stringify({body})},token);setComments(p=>[...p,c]);setBody('');}finally{setSaving(false)}};const update=async(patch:Record<string,unknown>)=>{try{await request(`/api/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify(patch)},token);onChanged();}catch(e){alert((e as Error).message)}};return <Modal title={task.title} onClose={onClose}><div className="task-detail"><div className="detail-grid"><div><span className={`priority-pill ${task.priority.toLowerCase()}`}>{task.priority}</span><p className="detail-description">{task.description||'No description.'}</p></div><div className="detail-controls"><label>Status<select value={task.columnId} onChange={e=>update({columnId:e.target.value})}>{project.columns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Assignee<select value={task.assignee?.id??''} onChange={e=>update({assigneeId:e.target.value||null})}><option value="">Unassigned</option>{project.members.map(m=><option key={m.user.id} value={m.user.id}>{m.user.name}</option>)}</select></label></div></div><hr/><h3>Discussion</h3><div className="comments">{comments.map(c=><div className="comment" key={c.id}><div className="comment-head"><strong>{c.author.name}</strong><span>{new Date(c.createdAt).toLocaleString()}</span></div><p>{c.body}</p></div>)}{!comments.length&&<p className="muted">No comments yet. Start the conversation.</p>}</div><form onSubmit={save} className="comment-form"><input value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a comment…"/><button className="primary" disabled={saving}>Send</button></form></div></Modal>;}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="ghost" onClick={onClose}>✕</button></div>{children}</div></div>;}
